"""Export every checkpoint (6 families x capacity sweep) to plain-C headers for the ESP32.

For each model we:
  1. load the checkpoint,
  2. reproduce its forward pass (label + a monotonic score) in pure NumPy,
  3. assert the NumPy labels match sklearn/xgboost/torch `.predict` on the embedded
     samples (parity gate), and
  4. emit weights + config tables into esp32/include/*.h, plus the shared DS2 sample set.

All 36 models are emitted; the firmware picks a subset per build group via -DINC_<FAMILY>
(the weights no longer fit one 3 MB partition — see esp32/platformio.ini). MODEL_FAM ids
are FIXED and must match the Family enum in esp32/src/main.cpp.

We also print the PC metrics (acc/precision/recall/f1/auc) on the embedded subset so the
on-device numbers can be cross-checked.

Run (from repo root):  PYTHONPATH=. ./env/bin/python tools/export_esp32.py
"""
from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
import torch
from sklearn.svm import SVC

from src import config
from src.data import build_dataset
from src.evaluation import compute_metrics
from src.io import model_path
from src.models.cnn import SWEEP as CNN_SIZES, ECGCNN
from src.models.crnn import SWEEP as CRNN_SIZES, ECGCRNN
from src.models.lstm import SWEEP as LSTM_SIZES, ECGLSTM
from src.models.rf import SWEEP as RF_SIZES
from src.models.svm import SWEEP as SVM_SIZES
from src.models.xgb import SWEEP as XGB_SIZES, base_logit, forward as xgb_forward, tree_arrays
from src.seeding import set_seed

# family -> id in the firmware's Family enum (main.cpp). Append only; never renumber.
FAM_ID = {"rf": 0, "svm": 1, "cnn": 2, "lstm": 3, "xgb": 4, "crnn": 5}

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "esp32" / "include"
OUT.mkdir(parents=True, exist_ok=True)

# Embedded beats are now used ONLY for the parity gate + per-beat LATENCY/RAM
# measurement on-device. Trustworthy quality comes from the full DS2 metrics JSONs on
# PC (parity == 1.0000 means on-device labels are bit-identical), so a tiny N keeps the
# ~24-model sweep fast even with the slow CNN/LSTM kernels.
N_SAMPLES = 20
SEED = 42
BN_EPS = 1e-5
sig = lambda z: 1.0 / (1.0 + np.exp(-z))


# ---------------- C emission ----------------
def arr(name, a, dtype="float"):
    flat = np.asarray(a).ravel()
    if dtype == "float":
        body = ", ".join(f"{v:.8e}f" for v in flat)
    else:
        body = ", ".join(str(int(v)) for v in flat)
    return f"static const {dtype} {name}[{max(flat.size,1)}] = {{{body if flat.size else '0'}}};\n"


def banner(t):
    return f"// === {t} (auto-generated by tools/export_esp32.py — do not edit) ===\n"


def stratified_indices(y, n, seed=SEED):
    rng = np.random.default_rng(seed)
    pos, neg = np.flatnonzero(y == 1), np.flatnonzero(y == 0)
    n_pos = max(1, int(round(n * pos.size / y.size)))
    idx = np.concatenate([rng.choice(pos, min(n_pos, pos.size), False),
                          rng.choice(neg, min(n - n_pos, neg.size), False)])
    rng.shuffle(idx)
    return np.sort(idx)


def metrics_row(name, y, pred, score):
    m = compute_metrics(y, pred, score)
    return (f"  {name:<11} acc={m['accuracy']:.4f}  p={m['precision']:.4f}  "
            f"r={m['recall']:.4f}  f1={m['f1']:.4f}  auc={m.get('roc_auc', float('nan')):.4f}")


# ---------------- NumPy reproductions (label, score) ----------------
def rf_forward(model, X):
    p1 = np.zeros(len(X))
    for tr in model.estimators_:
        t = tr.tree_
        for i, x in enumerate(X):
            nd = 0
            while t.children_left[nd] != -1:
                nd = t.children_left[nd] if x[t.feature[nd]] <= t.threshold[nd] else t.children_right[nd]
            v = t.value[nd][0]
            p1[i] += v[1] / v.sum()
    p1 /= len(model.estimators_)
    return (p1 > 0.5).astype(np.int64), p1


def svm_forward(pipe, X):
    sc, clf = pipe.named_steps["scaler"], pipe.named_steps["clf"]
    Xs = (X - sc.mean_) / sc.scale_
    if isinstance(clf, SVC):                                   # RBF
        sv, dual = clf.support_vectors_, clf.dual_coef_[0]
        d2 = ((Xs[:, None, :] - sv[None, :, :]) ** 2).sum(-1)  # (N, n_sv)
        dec = (dual * np.exp(-clf._gamma * d2)).sum(1) + clf.intercept_[0]
        return (dec > 0).astype(np.int64), dec
    p = np.zeros(len(X))                                       # linear + calibration
    for cc in clf.calibrated_classifiers_:
        d = Xs @ cc.estimator.coef_[0] + cc.estimator.intercept_[0]
        cal = cc.calibrators[0]
        p += sig(-(cal.a_ * d + cal.b_))
    p /= len(clf.calibrated_classifiers_)
    return (p >= 0.5).astype(np.int64), p


def fold_convs(sd):
    """BN-folded conv stack (list of (w, b)), shared by the CNN and the CRNN front-end."""
    layers, i = [], 0
    while f"features.{i}.block.0.weight" in sd:
        w = sd[f"features.{i}.block.0.weight"].numpy()
        b = sd[f"features.{i}.block.0.bias"].numpy()
        g = sd[f"features.{i}.block.1.weight"].numpy()
        be = sd[f"features.{i}.block.1.bias"].numpy()
        rm = sd[f"features.{i}.block.1.running_mean"].numpy()
        rv = sd[f"features.{i}.block.1.running_var"].numpy()
        s = g / np.sqrt(rv + BN_EPS)
        layers.append((w * s[:, None, None], s * (b - rm) + be))
        i += 1
    return layers


def conv_stack(layers, x):
    """Run the Conv-ReLU-MaxPool stack on one beat -> channel-major activations [C, L']."""
    a = x[None, :]
    for (w, b) in layers:
        oc, k = w.shape[0], w.shape[2]
        pad = k // 2
        L = a.shape[1]
        ap = np.pad(a, ((0, 0), (pad, pad)))
        conv = np.empty((oc, L))
        for c in range(oc):
            for t in range(L):
                conv[c, t] = np.sum(ap[:, t:t + k] * w[c]) + b[c]
        conv = np.maximum(conv, 0.0)
        Lh = L // 2
        a = conv[:, :Lh * 2].reshape(oc, Lh, 2).max(2)
    return a


def cnn_layers(sd):
    """Return list of (folded_w, folded_b) conv layers + a head descriptor."""
    layers = fold_convs(sd)
    if "head.1.weight" in sd:   # Flatten -> Linear -> ReLU -> Dropout -> Linear
        head = ("fc", sd["head.1.weight"].numpy(), sd["head.1.bias"].numpy(),
                sd["head.4.weight"].numpy(), sd["head.4.bias"].numpy())
    else:                       # GAP -> Linear
        head = ("gap", sd["head.2.weight"].numpy(), sd["head.2.bias"].numpy())
    return layers, head


def cnn_forward(layers, head, X):
    preds, scores = [], []
    for x in X:
        a = conv_stack(layers, x)
        if head[0] == "gap":
            logits = head[1] @ a.mean(1) + head[2]
        else:
            h = np.maximum(head[1] @ a.reshape(-1) + head[2], 0.0)
            logits = head[3] @ h + head[4]
        preds.append(int(np.argmax(logits)))
        scores.append(float(logits[1] - logits[0]))
    return np.array(preds, np.int64), np.array(scores)


def crnn_forward(convs, lstm_layers_, hw, hb, X):
    """Conv front-end, then one LSTM pass over the pooled map, classify on the last h."""
    (Wih, Whh, bih, bhh) = lstm_layers_[0]
    H = Whh.shape[1]
    preds, scores = [], []
    for x in X:
        a = conv_stack(convs, x)                # [C, T]
        h = np.zeros(H); c = np.zeros(H)
        for t in range(a.shape[1]):
            g = Wih @ a[:, t] + bih + Whh @ h + bhh
            gi, gf, gg, go = g[:H], g[H:2 * H], g[2 * H:3 * H], g[3 * H:]
            c = sig(gf) * c + sig(gi) * np.tanh(gg)
            h = sig(go) * np.tanh(c)
        logits = hw @ h + hb
        preds.append(int(np.argmax(logits)))
        scores.append(float(logits[1] - logits[0]))
    return np.array(preds, np.int64), np.array(scores)


def lstm_layers(sd):
    layers, i = [], 0
    while f"lstm.weight_ih_l{i}" in sd:
        layers.append((sd[f"lstm.weight_ih_l{i}"].numpy(), sd[f"lstm.weight_hh_l{i}"].numpy(),
                       sd[f"lstm.bias_ih_l{i}"].numpy(), sd[f"lstm.bias_hh_l{i}"].numpy()))
        i += 1
    return layers, sd["head.weight"].numpy(), sd["head.bias"].numpy()


def lstm_forward(layers, hw, hb, X):
    preds, scores = [], []
    for seq in X:
        inp = seq[:, None]
        for (Wih, Whh, bih, bhh) in layers:
            H = Whh.shape[1]
            h = np.zeros(H); c = np.zeros(H); outs = []
            for t in range(inp.shape[0]):
                g = Wih @ inp[t] + bih + Whh @ h + bhh
                i, f, gg, o = g[:H], g[H:2 * H], g[2 * H:3 * H], g[3 * H:]
                c = sig(f) * c + sig(i) * np.tanh(gg)
                h = sig(o) * np.tanh(c)
                outs.append(h.copy())
            inp = np.array(outs)
        logits = hw @ inp[-1] + hb
        preds.append(int(np.argmax(logits)))
        scores.append(float(logits[1] - logits[0]))
    return np.array(preds, np.int64), np.array(scores)


# torch references
def torch_cnn_pred(sz, channels, fc, sd, X):
    m = ECGCNN(channels, fc); m.load_state_dict(sd); m.eval()
    with torch.no_grad():
        return m(torch.from_numpy(X).float().unsqueeze(1)).argmax(1).numpy()


def torch_lstm_pred(hidden, layers, sd, X):
    m = ECGLSTM(hidden, layers, False); m.load_state_dict(sd); m.eval()
    with torch.no_grad():
        return m(torch.from_numpy(X).float().unsqueeze(-1)).argmax(1).numpy()


def torch_crnn_pred(channels, hidden, sd, X):
    m = ECGCRNN(channels, hidden); m.load_state_dict(sd); m.eval()
    with torch.no_grad():
        return m(torch.from_numpy(X).float().unsqueeze(1)).argmax(1).numpy()


# ---------------- main ----------------
def main():
    set_seed(SEED)
    *_, Xf_te, yf = build_dataset(mode="features")
    *_, Xr_te, yr = build_dataset(mode="raw")
    *_, Xl_te, yl = build_dataset(mode="lstm")
    assert np.array_equal(yf, yr) and np.array_equal(yf, yl)
    idx = stratified_indices(yf, N_SAMPLES)
    y_true, feat, raw, seq = yf[idx], Xf_te[idx], Xr_te[idx], Xl_te[idx]
    nf = feat.shape[1]
    print(f"[export] N={len(idx)} pos={y_true.mean():.3f} n_feat={nf}\n[export] PC metrics on the {len(idx)} embedded samples:")
    preds_all = []   # one row of length N per model, in firmware order

    rf_h = banner("Random Forest: capacity sweep"); rf_cfg = []
    for k, (sz, n_est, depth) in enumerate(RF_SIZES):
        m = joblib.load(model_path("rf", sz, "pkl"))
        pred, score = rf_forward(m, feat)
        assert np.array_equal(pred, m.predict(feat)), f"RF {sz} parity FAIL"
        print(metrics_row(f"rf_{sz}", y_true, pred, score)); preds_all.append(pred)
        rf_h += _emit_rf(k, m, nf); rf_cfg.append((k, len(m.estimators_), nf))
    rf_h += _rf_table(rf_cfg)
    (OUT / "model_rf.h").write_text(rf_h)

    xgb_h = banner("XGBoost: capacity sweep (strict '<' splits, leaf logits summed)"); xgb_cfg = []
    for k, (sz, _n, _d) in enumerate(XGB_SIZES):
        m = joblib.load(model_path("xgb", sz, "pkl"))
        trees, b0 = tree_arrays(m), base_logit(m)
        pred, score = xgb_forward(trees, b0, feat)
        assert np.array_equal(pred, m.predict(feat)), f"XGB {sz} parity FAIL"
        print(metrics_row(f"xgb_{sz}", y_true, pred, score)); preds_all.append(pred)
        xgb_h += _emit_xgb(k, trees); xgb_cfg.append((k, len(trees), nf, b0))
    xgb_h += _xgb_table(xgb_cfg)
    (OUT / "model_xgb.h").write_text(xgb_h)

    svm_h = banner("SVM: tiny=linear+calibration, rest=RBF"); svm_cfg = []
    for k, (sz, kernel, _) in enumerate(SVM_SIZES):
        pipe = joblib.load(model_path("svm", sz, "pkl"))
        pred, score = svm_forward(pipe, feat)
        assert np.array_equal(pred, pipe.predict(feat)), f"SVM {sz} parity FAIL"
        print(metrics_row(f"svm_{sz}", y_true, pred, score)); preds_all.append(pred)
        h, c = _emit_svm(k, pipe, nf); svm_h += h; svm_cfg.append(c)
    svm_h += _svm_table(svm_cfg)
    (OUT / "model_svm.h").write_text(svm_h)

    cnn_h = banner("1D CNN: capacity sweep (GAP or FC head, BN folded)"); cnn_cfg = []
    cnn_buf = 0
    for k, (sz, channels, fc) in enumerate(CNN_SIZES):
        sd = torch.load(model_path("cnn", sz, "pt"), map_location="cpu")
        layers, head = cnn_layers(sd)
        pred, score = cnn_forward(layers, head, raw)
        assert np.array_equal(pred, torch_cnn_pred(sz, channels, fc, sd, raw)), f"CNN {sz} parity FAIL"
        print(metrics_row(f"cnn_{sz}", y_true, pred, score)); preds_all.append(pred)
        h, c, b = _emit_cnn(k, layers, head, config.BEAT_LEN); cnn_h += h; cnn_cfg.append(c); cnn_buf = max(cnn_buf, b)
    cnn_h = f"#define CNN_BUF {cnn_buf}\n" + cnn_h + _cnn_table(cnn_cfg)
    (OUT / "model_cnn.h").write_text(cnn_h)

    lstm_h = banner("LSTM: capacity sweep (last point is 2-layer)"); lstm_cfg = []
    lstm_buf = 0
    for k, (sz, hidden, nlayers) in enumerate(LSTM_SIZES):
        sd = torch.load(model_path("lstm", sz, "pt"), map_location="cpu")
        layers, hw, hb = lstm_layers(sd)
        pred, score = lstm_forward(layers, hw, hb, seq)
        assert np.array_equal(pred, torch_lstm_pred(hidden, nlayers, sd, seq)), f"LSTM {sz} parity FAIL"
        print(metrics_row(f"lstm_{sz}", y_true, pred, score)); preds_all.append(pred)
        h, c, b = _emit_lstm(k, layers, hw, hb, config.LSTM_SEQ_LEN); lstm_h += h; lstm_cfg.append(c); lstm_buf = max(lstm_buf, b)
    lstm_h = f"#define LSTM_BUF {lstm_buf}\n" + lstm_h + _lstm_table(lstm_cfg)
    (OUT / "model_lstm.h").write_text(lstm_h)

    crnn_h = banner("CRNN: conv front-end (BN folded) -> 1-layer LSTM on the pooled map"); crnn_cfg = []
    crnn_buf = 0
    for k, (sz, channels, hidden) in enumerate(CRNN_SIZES):
        sd = torch.load(model_path("crnn", sz, "pt"), map_location="cpu")
        convs = fold_convs(sd)
        lstm_l, hw, hb = lstm_layers(sd)
        pred, score = crnn_forward(convs, lstm_l, hw, hb, raw)
        assert np.array_equal(pred, torch_crnn_pred(channels, hidden, sd, raw)), f"CRNN {sz} parity FAIL"
        print(metrics_row(f"crnn_{sz}", y_true, pred, score)); preds_all.append(pred)
        h, c, b = _emit_crnn(k, convs, lstm_l, hw, hb, config.BEAT_LEN)
        crnn_h += h; crnn_cfg.append(c); crnn_buf = max(crnn_buf, b)
    crnn_h = f"#define CRNN_BUF {crnn_buf}\n" + crnn_h + _crnn_table(crnn_cfg)
    (OUT / "model_crnn.h").write_text(crnn_h)

    # Model table. Firmware order == Y_PC row order; each model keeps its GLOBAL index so
    # a build group that compiles only a subset still checks parity against the right row.
    meta = [(fam, s[0], FAM_ID[fam]) for fam, sizes in
            (("rf", RF_SIZES), ("xgb", XGB_SIZES), ("svm", SVM_SIZES),
             ("cnn", CNN_SIZES), ("lstm", LSTM_SIZES), ("crnn", CRNN_SIZES))
            for s in sizes]
    _emit_test_data(nf, y_true, feat, raw, seq, np.array(preds_all), meta)
    print(f"[export] all parity gates passed; headers written to {OUT}")


# ---------------- emitters ----------------
def _emit_rf(k, model, nf):
    feat, thr, left, right, p1, off = [], [], [], [], [], [0]
    for t in model.estimators_:
        tt = t.tree_
        for nd in range(tt.node_count):
            leaf = tt.children_left[nd] == -1
            feat.append(tt.feature[nd] if not leaf else -1)
            thr.append(tt.threshold[nd]); left.append(tt.children_left[nd]); right.append(tt.children_right[nd])
            v = tt.value[nd][0]; p1.append(v[1] / v.sum())
        off.append(off[-1] + tt.node_count)
    return (arr(f"RF{k}_OFF", off, "int") + arr(f"RF{k}_FEAT", feat, "int") + arr(f"RF{k}_THR", thr) +
            arr(f"RF{k}_L", left, "int") + arr(f"RF{k}_R", right, "int") + arr(f"RF{k}_P1", p1))


def _rf_table(cfg):
    rows = ",\n".join(f"  {{{n}, {nf}, RF{k}_OFF, RF{k}_FEAT, RF{k}_L, RF{k}_R, RF{k}_THR, RF{k}_P1}}"
                      for (k, n, nf) in cfg)
    return f"static const RFCfg RF_CFG[{len(cfg)}] = {{\n{rows}\n}};\n"


def _emit_xgb(k, trees):
    """Same node layout as the RF, but leaves carry logit contributions (already shrunk by
    the learning rate) instead of class probabilities."""
    feat, thr, left, right, leaf, off = [], [], [], [], [], [0]
    for t in trees:
        feat += t["feature"]; thr += t["thr"]; left += t["left"]
        right += t["right"]; leaf += t["leaf"]
        off.append(off[-1] + len(t["feature"]))
    return (arr(f"XGB{k}_OFF", off, "int") + arr(f"XGB{k}_FEAT", feat, "int") + arr(f"XGB{k}_THR", thr) +
            arr(f"XGB{k}_L", left, "int") + arr(f"XGB{k}_R", right, "int") + arr(f"XGB{k}_LEAF", leaf))


def _xgb_table(cfg):
    rows = ",\n".join(
        f"  {{{n}, {nf}, XGB{k}_OFF, XGB{k}_FEAT, XGB{k}_L, XGB{k}_R, XGB{k}_THR, "
        f"XGB{k}_LEAF, {b0:.8e}f}}" for (k, n, nf, b0) in cfg)
    return f"static const XGBCfg XGB_CFG[{len(cfg)}] = {{\n{rows}\n}};\n"


def _emit_svm(k, pipe, nf):
    sc, clf = pipe.named_steps["scaler"], pipe.named_steps["clf"]
    h = arr(f"SVM{k}_MEAN", sc.mean_) + arr(f"SVM{k}_SCALE", sc.scale_)
    if isinstance(clf, SVC):
        h += arr(f"SVM{k}_SV", clf.support_vectors_) + arr(f"SVM{k}_DUAL", clf.dual_coef_[0])
        row = (f"  {{1, {nf}, SVM{k}_MEAN, SVM{k}_SCALE, 0, 0,0,0,0, "
               f"{clf.support_vectors_.shape[0]}, SVM{k}_SV, SVM{k}_DUAL, {clf._gamma:.8e}f, {clf.intercept_[0]:.8e}f}}")
    else:
        coef = np.array([cc.estimator.coef_[0] for cc in clf.calibrated_classifiers_])
        inter = np.array([cc.estimator.intercept_[0] for cc in clf.calibrated_classifiers_])
        a = np.array([cc.calibrators[0].a_ for cc in clf.calibrated_classifiers_])
        b = np.array([cc.calibrators[0].b_ for cc in clf.calibrated_classifiers_])
        h += (arr(f"SVM{k}_COEF", coef) + arr(f"SVM{k}_INT", inter) +
              arr(f"SVM{k}_A", a) + arr(f"SVM{k}_B", b))
        row = (f"  {{0, {nf}, SVM{k}_MEAN, SVM{k}_SCALE, {len(coef)}, "
               f"SVM{k}_COEF, SVM{k}_INT, SVM{k}_A, SVM{k}_B, 0, 0,0, 0.0f, 0.0f}}")
    return h, row


def _svm_table(rows):
    return f"static const SVMCfg SVM_CFG[{len(rows)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def _emit_cnn(k, layers, head, in_len):
    in_ch, out_ch, w_off, b_off, W, B = [], [], [0], [0], [], []
    L = in_len; buf = in_len
    for (w, b) in layers:
        in_ch.append(w.shape[1]); out_ch.append(w.shape[0])
        W.append(w.ravel()); B.append(b)
        w_off.append(w_off[-1] + w.size); b_off.append(b_off[-1] + b.size)
        L //= 2
        buf = max(buf, w.shape[0] * L)        # pooled activation size
    K = layers[0][0].shape[2]
    h = arr(f"CNN{k}_W", np.concatenate(W)) + arr(f"CNN{k}_B", np.concatenate(B))
    h += arr(f"CNN{k}_INCH", in_ch, "int") + arr(f"CNN{k}_OUTCH", out_ch, "int")
    h += arr(f"CNN{k}_WOFF", w_off, "int") + arr(f"CNN{k}_BOFF", b_off, "int")
    last_c = out_ch[-1]
    if head[0] == "gap":
        h += arr(f"CNN{k}_FC2W", head[1]) + arr(f"CNN{k}_FC2B", head[2])
        fc_hidden, flat = 0, 0
        fc1 = "0, 0"
    else:
        flat = head[1].shape[1]; fc_hidden = head[1].shape[0]
        h += (arr(f"CNN{k}_FC1W", head[1]) + arr(f"CNN{k}_FC1B", head[2]) +
              arr(f"CNN{k}_FC2W", head[3]) + arr(f"CNN{k}_FC2B", head[4]))
        fc1 = f"CNN{k}_FC1W, CNN{k}_FC1B"
        buf = max(buf, flat)
    row = (f"  {{{len(layers)}, {K}, {K//2}, {in_len}, CNN{k}_INCH, CNN{k}_OUTCH, "
           f"CNN{k}_WOFF, CNN{k}_BOFF, CNN{k}_W, CNN{k}_B, {fc_hidden}, {flat}, {last_c}, "
           f"{fc1}, CNN{k}_FC2W, CNN{k}_FC2B}}")
    return h, row, buf


def _cnn_table(rows):
    return f"static const CNNCfg CNN_CFG[{len(rows)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def _emit_lstm(k, layers, hw, hb, seq_len):
    wih_off, whh_off, WIH, WHH, BIH, BHH = [0], [0], [], [], [], []
    H = layers[0][1].shape[1]
    for (Wih, Whh, bih, bhh) in layers:
        WIH.append(Wih.ravel()); WHH.append(Whh.ravel()); BIH.append(bih); BHH.append(bhh)
        wih_off.append(wih_off[-1] + Wih.size); whh_off.append(whh_off[-1] + Whh.size)
    h = (arr(f"LSTM{k}_WIH", np.concatenate(WIH)) + arr(f"LSTM{k}_WHH", np.concatenate(WHH)) +
         arr(f"LSTM{k}_BIH", np.concatenate(BIH)) + arr(f"LSTM{k}_BHH", np.concatenate(BHH)) +
         arr(f"LSTM{k}_WIHOFF", wih_off, "int") + arr(f"LSTM{k}_WHHOFF", whh_off, "int") +
         arr(f"LSTM{k}_HW", hw) + arr(f"LSTM{k}_HB", hb))
    row = (f"  {{{len(layers)}, {H}, {seq_len}, LSTM{k}_WIHOFF, LSTM{k}_WHHOFF, "
           f"LSTM{k}_WIH, LSTM{k}_WHH, LSTM{k}_BIH, LSTM{k}_BHH, LSTM{k}_HW, LSTM{k}_HB}}")
    return h, row, seq_len * H


def _lstm_table(rows):
    return f"static const LSTMCfg LSTM_CFG[{len(rows)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def _emit_crnn(k, convs, lstm_l, hw, hb, in_len):
    in_ch, out_ch, w_off, b_off, W, B = [], [], [0], [0], [], []
    L = in_len; buf = 0
    for (w, b) in convs:
        in_ch.append(w.shape[1]); out_ch.append(w.shape[0])
        W.append(w.ravel()); B.append(b)
        w_off.append(w_off[-1] + w.size); b_off.append(b_off[-1] + b.size)
        L //= 2
        buf = max(buf, w.shape[0] * L)        # pooled activation size (channel-major)
    K = convs[0][0].shape[2]
    Wih, Whh, bih, bhh = lstm_l[0]            # CRNN is always a single LSTM layer
    H = Whh.shape[1]
    h = (arr(f"CRNN{k}_W", np.concatenate(W)) + arr(f"CRNN{k}_B", np.concatenate(B)) +
         arr(f"CRNN{k}_INCH", in_ch, "int") + arr(f"CRNN{k}_OUTCH", out_ch, "int") +
         arr(f"CRNN{k}_WOFF", w_off, "int") + arr(f"CRNN{k}_BOFF", b_off, "int") +
         arr(f"CRNN{k}_WIH", Wih) + arr(f"CRNN{k}_WHH", Whh) +
         arr(f"CRNN{k}_BIH", bih) + arr(f"CRNN{k}_BHH", bhh) +
         arr(f"CRNN{k}_HW", hw) + arr(f"CRNN{k}_HB", hb))
    row = (f"  {{{len(convs)}, {K}, {K // 2}, {in_len}, CRNN{k}_INCH, CRNN{k}_OUTCH, "
           f"CRNN{k}_WOFF, CRNN{k}_BOFF, CRNN{k}_W, CRNN{k}_B, {L}, {out_ch[-1]}, {H}, "
           f"CRNN{k}_WIH, CRNN{k}_WHH, CRNN{k}_BIH, CRNN{k}_BHH, CRNN{k}_HW, CRNN{k}_HB}}")
    return h, row, buf


def _crnn_table(rows):
    return f"static const CRNNCfg CRNN_CFG[{len(rows)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def _emit_test_data(nf, y_true, feat, raw, seq, preds_all, meta):
    h = banner("Embedded DS2 sample set (shared by all models)")
    h += f"#define N_SAMPLES {len(y_true)}\n#define N_FEAT {nf}\n#define NUM_MODELS {len(preds_all)}\n"
    h += f"#define RAW_LEN {raw.shape[1]}\n#define SEQ_LEN {seq.shape[1]}\n"
    h += arr("Y_TRUE", y_true, "int") + arr("FEAT", feat) + arr("RAW", raw) + arr("SEQ", seq)
    h += arr("Y_PC", preds_all, "int")   # [NUM_MODELS * N_SAMPLES], firmware order
    # model table (firmware builds the dispatch list from this, so it scales with the sweep)
    names = ", ".join(f'"{fam}_{label}"' for (fam, label, _) in meta)
    fams = ", ".join(str(f) for (_, _, f) in meta)               # see FAM_ID / Family enum
    subs, ctr = [], {}
    for (_, _, f) in meta:
        subs.append(ctr.get(f, 0)); ctr[f] = ctr.get(f, 0) + 1   # index within family
    h += f"static const char *MODEL_NAMES[NUM_MODELS] = {{{names}}};\n"
    h += f"static const int MODEL_FAM[NUM_MODELS] = {{{fams}}};\n"
    h += f"static const int MODEL_SUB[NUM_MODELS] = {{{', '.join(str(s) for s in subs)}}};\n"
    (OUT / "test_data.h").write_text(h)


if __name__ == "__main__":
    main()
